### ISSUE TITLE
Gotta say THANKS

### ISSUE THREAD

**Issue by rmasci** [bwmarrin/sql2xlsx#2]
For a few years I've been doing this exact thing using "github.com/360EntSecGroup-Skylar/excelize" -- I don't know if it was me, but that package kept changing their code and breaking mine. I needed it to work ASAP -- day before vacation, gotta get a report out FAST and my tool didn't work. Then I stumbled on your code looking for a replacement to excelize. I was able to take your generateXLSXFromRows -- copied and pasted it in to replace my generateExcel  function -- it worked!  Just wanted to say thank you for that. 

My code is a general query tool that formats in csv, mysql tables, text, html, json (formatted) etc. if you want I could give you a pull request with the other formats...

**Comment by bwmarrin** [comment]
Awesome, nice to hear it was helpful to you!  It would be cool to see the other formats you've done.  I've done something similar with another project where I have a converted for a handful of formats.  Make a repo for it and share it here for others :)
